/**
 * HTTP statuses code list
 */
const HTTP_STATUS_CODE_LIST = {};

HTTP_STATUS_CODE_LIST.OK = 200;
HTTP_STATUS_CODE_LIST.FORBIDDEN = 403;
HTTP_STATUS_CODE_LIST.UNPROCESSABLE_ENTITY = 422;
HTTP_STATUS_CODE_LIST.INTERNAL_SERVER_ERROR = 500;

Object.freeze(HTTP_STATUS_CODE_LIST);

module.exports = HTTP_STATUS_CODE_LIST;
