/**
 * Database state list
 */
const DATABASE_STATE_LIST = {};

DATABASE_STATE_LIST.STATE_CONNECTED = 0;
DATABASE_STATE_LIST.STATE_CONNECTING = 1;
DATABASE_STATE_LIST.STATE_DISCONNECTED = 2;

Object.freeze(DATABASE_STATE_LIST);

module.exports = DATABASE_STATE_LIST;
